language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
    - composer update --prefer-dist

script: if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
